
services:
  postgres:
    image: postgres:15-alpine
    container_name: middleware-postgres
    environment:
      POSTGRES_DB: middleware
      POSTGRES_USER: middleware
      POSTGRES_PASSWORD: middleware
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
